apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-service-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: diploma
  source:
    repoURL: https://github.com/Svetlioo/diplomna-rabota-gitops.git
    targetRevision: main
    path: helm-charts/bank-service
    helm:
      valueFiles:
        - ../../environments/prod/values-bank.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
