apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-detection-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: diploma
  source:
    repoURL: https://github.com/Svetlioo/diplomna-rabota-gitops.git
    targetRevision: main
    path: helm-charts/fraud-detection
    helm:
      valueFiles:
        - ../../environments/test/values-fraud.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
